In [6]:
import numpy as np #full form is numerical python

l1=[4,5,8,9]
l2=[7,9,7,3]
print(l1+l2)

In [7]:
l1=[4,5,8,9]
l2=[7,9,7,3]
l3=8
print(l1+l2)

[4, 5, 8, 9, 7, 9, 7, 3]


In [8]:
print(l1*l3)

[4, 5, 8, 9, 4, 5, 8, 9, 4, 5, 8, 9, 4, 5, 8, 9, 4, 5, 8, 9, 4, 5, 8, 9, 4, 5, 8, 9, 4, 5, 8, 9]


In [9]:
#in list no mathematical operations are happenning so we use numpy array 

In [10]:
a1=np.array([2,3,4,5,6])
a2=np.array([4,5,6,7,2])
a3=9

In [11]:
print(a1)
print(a1+a2)
print(a2*a3)
print(a1*a2)

[2 3 4 5 6]
[ 6  8 10 12  8]
[36 45 54 63 18]
[ 8 15 24 35 12]


In [12]:
#in abpve array we perform mathematical operations which we cant perform before in list
#in array we can store the value of single data type
#list cannot handel direct mathematical operations like arrays do
#array consume less memory compated to list
#list can store different data types but not arrays
#list is easier to modify than numpy array 
# in list we dont care about size but we have to care in array



In [13]:
li=[[2,3,4,5,7],[5,6]]
ar=np.array([[5,6,7,0],[7,8,1,4]]) #dimension must be cared
print(li)
print(ar)

[[2, 3, 4, 5, 7], [5, 6]]
[[5 6 7 0]
 [7 8 1 4]]
