import numpy as np

In [5]:
import numpy as np

In [6]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2,3],[4,5,6]])
a3=np.zeros(5)
a4=np.ones((2,3))
print(a1)
print(a2)
print(a3)
print(a4)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
a5=np.full((2,2),7)
print(a5)

[[7 7]
 [7 7]]


In [12]:
#creating sequences of numbers in numpy
arr=np.arange(1,10,2)     #arrange function workd as range function -this give result from 2 to 10 with 2 difference
print(arr)

[1 3 5 7 9]


In [15]:
#creating identity matrix
i1=np.eye(4)
print(i1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#this all are numpy array creation methods