In [16]:
#chapter 2-Array properties and operations

In [27]:
import numpy as np
#all about checking the array
a1=np.array([[[2,3,4,5],[6,7,8,9]],[[2,3,9,10],[2,3,9,10]]])
print(a1.shape)
print(a1.size)
print(a1.ndim)   #ndim is used to check number of dimensions
print(a1.dtype)  #used to check data type of element

(2, 2, 4)
16
3
int64


In [30]:
#method to convert one type of data into another
a2=np.array([1.1,2.2,3.3,8.8])
print(a2)
print(a2.dtype)
a3=a2.astype(int)
print(a2)
print(a3)
print(a3.dtype)

[1.1 2.2 3.3 8.8]
float64
[1.1 2.2 3.3 8.8]
[1 2 3 8]
int64


In [31]:
#mathematical operations in array
a4=np.array([2,3,4,5,6])
print(a4+6)
print(a4*9)
print(a4**2)  #double multiply to calculate square

[ 8  9 10 11 12]
[18 27 36 45 54]
[ 4  9 16 25 36]


In [33]:
#aggregation function
a5=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.mean(a5))
print(np.sum(a5))
print(np.min(a5))
print(np.max(a5))
print(np.std(a5))     #std is used to calculate standard deviation
print(np.var(a5))     #to calculate variance

5.5
55
1
10
2.8722813232690143
8.25
