In [6]:
#chapter 3: indexing and slicing
#indexing is used we we need to pick single element
#in slicing we can pick multiple element
#in slicing we have to pass start, stop and step

In [7]:
#fancy indexing: selecting multiple element at same using list of indices
#Boolean masaking: 
#negative indexing-> Right tp left indexing

In [2]:
import numpy as np
a1=np.array([2,3,4,5,6,7,0])
print(a1[0])
print(a1[-2])


2
7


In [3]:
a2=np.array([[2,3,9],[4,1,7],[4,1,7]])
print(a2[2][1])

1


In [5]:
#slicing
a3=np.array([1,2,3,4,9,0,6,7,9])
print(a3[1:4])
print(a3[::-1])
print(a3[:4])
print(a3[1:8:2])

[2 3 4]
[9 7 6 0 9 4 3 2 1]
[1 2 3 4]
[2 4 0 7]


In [7]:
print(a3[[2,3,6,1]])

[3 4 6 2]


In [13]:
#boolean masking:-> filterimg data based on condition- we can filterelement based on some given condition
a4=np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5])
print(a4[a4>5])
print(a4[a4<7])    #boolean mastering is 10 times faster instead of using loops in data filtering

[6 7 8 9]
[1 2 3 4 5 6 1 2 3 4 5]
