In [2]:
#Reshaping and manupulation array

In [6]:
#REshape-it specify new shape
#we can only reshape if dimension match
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.reshape(2,3))
print(arr.reshape(3,2))   #reshaping doesnot create copy changine in reshap can change original array

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
#flattering arrays
#-ravel and -flatter
#.ravel()->it return a view i.e modification in original array
#.flatten()-> returns a copy
ar1=np.array([[2,3,4],[1,3,5]])
print(ar1.ravel())
print(ar1.flatten())     #this both function convert array in 1d

[2 3 4 1 3 5]
[2 3 4 1 3 5]
