In [2]:
#Advance python
import numpy as np

In [15]:
"""
insert ->np.insert(array,index, value, axis=None)
axis-(none-> means inserting in flattern array),(0->rowwise insert),(1_>column wise inssert)
"""
a1=np.array([[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9]])
print(a1)
a2=np.insert(a1,5,10)    
print(a2)
a3=np.insert(a1,1,[2,3],axis=1)
print(a3)

[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]]
[ 1  2  3  4  5 10  6  7  8  2  3  4  5  6  7  8  9]
[[1 2 2 3 4 5 6 7 8]
 [2 3 3 4 5 6 7 8 9]]


In [19]:
#append
a4=np.array([2,3,4])
print(a4)
a5=np.append(a4,1)
print(a5)
a6=np.append(a3,[2,7])
print(a6)

[2 3 4]
[2 3 4 1]
[1 2 2 3 4 5 6 7 8 2 3 3 4 5 6 7 8 9 2 7]


In [21]:
#if we want to join two arrays
b1=np.array([1,2])
b2=np.array([3,4])
print(np.append(b1,b2))

[1 2 3 4]


In [25]:
#concatenate function
c1=np.array([[1,2,3],[2,3,4]])
c2=np.array([[1,7,3],[9,3,0]])
c3=np.concatenate((c1,c2),axis=0)
c4=np.concatenate((c1,c2),axis=1)
print(c3)
print(c4)

[[1 2 3]
 [2 3 4]
 [1 7 3]
 [9 3 0]]
[[1 2 3 1 7 3]
 [2 3 4 9 3 0]]


In [27]:
"""
delete-> np.delete(array, index, axix=None)
"""
d1=np.array([1,2,3,4,5])
d2=np.delete(d1,1)
print(d2)

[1 3 4 5]


In [33]:
d3=np.array([[1,2,3],[4,5,6]])
print(d3)
d4=np.delete(d3,0,axis=0)
print(d4)
d4=np.delete(d3,0,axis=1)
print(d4)

[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[[2 3]
 [5 6]]


In [35]:
"""
stacking:
->vstack()   rowise or vertically
->hstack()   columnwise or horizontally
"""
e1=np.array([1,2,3])
e2=np.array([8,9,10])
print(np.vstack((e1,e2)))
print(np.hstack((e1,e2)))

[[ 1  2  3]
 [ 8  9 10]]
[ 1  2  3  8  9 10]


In [36]:
"""spliting::
np.split(array,part)
hsplit()
vsplit()
"""
f1=np.array([1,2,3,4,5,6])
print(np.split(f1,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [39]:
f2=np.array([[2,3],[4,5]])
print(f2)
print(np.vsplit(f2,2))

[[2 3]
 [4 5]]
[array([[2, 3]]), array([[4, 5]])]
