In [5]:
import numpy as np

In [3]:
"""Broadcasting and vectorization"""
#broadcasting is a numpy way where we prform operation on different size of array
#allowing 10% discount on products without using broadcasting
l1=[100,200,400]
l2=[]
for i in l1:
    dp=i-(i*10/100)
    l2.append(dp)
print(l1)
print(l2)

[100, 200, 400]
[90.0, 180.0, 360.0]


In [4]:
#working like this on real is too slow so broadcasting is its solution
a1=np.array([100,200,400])
a2=a1-(a1*10/100)
print(a2)


[ 90. 180. 360.]


In [8]:
a3=np.array([1,2,3,4,5])
a4=a3*2       #in this way broadcasting of single value is done
print(a4)      #we dont need to use for lopp to mumtiply every elements

[ 2  4  6  8 10]


In [11]:
matrix=np.array([[10,20,30],[40,50,60]])
vector=np.array([1,2,3])
result=matrix+vector        #broadcasting with maching dimension
print(result)

[[11 22 33]
 [41 52 63]]


In [1]:
m=np.array([[10,20,30],[40,50,60]])
v=np.array([1,2])
r=m+v        #broadcasting with non maching dimension
print(r)      #it throw error in incompatiable shapes

NameError: name 'np' is not defined

In [3]:
#vectorization
#if we use one operation in every element of array without loops is called vactorization
l1=[1,2,3]
l2=[4,5,6]
result=[x+y for x,y in zip(l1,l2)] #this is slow loop approach
print(result)

[5, 7, 9]


In [8]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
re=v1+v2        #this is vectorization approach . It is too fast than looop
print(re)

[5 7 9]


In [11]:
v3=np.array([1,2,3,4,5,6])
n=9
res=v3*n      #this is tooo fast we use this in deep learning
print(res)      #we use vectorization in matrix operation

[ 9 18 27 36 45 54]
